name: 'build-test'

on:
  # Trigger on pull requests and pushes to main or release branches
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run plugin check
        uses: wordpress/plugin-check-action@v1
